services:
  server:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./resources:/app/resources

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: jira
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
      interval: 2s
      timeout: 30s
      retries: 10
    env_file:
      - .env

  db-test:
    image: postgres:16
    environment:
      POSTGRES_USER: ${TEST_DB_USERNAME}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: jira-test
    ports:
      - '5433:5432'
    volumes:
      - ./db-test-data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ./db-data
      o: bind
  db-test-data:
    driver: local
    driver_opts:
      type: none
      device: ./db-test-data
      o: bind